-- MySQL Script generated by MySQL Workbench
-- Thu Feb 16 11:39:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema maacsport
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `maacsport` ;

-- -----------------------------------------------------
-- Schema maacsport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maacsport` DEFAULT CHARACTER SET latin1 ;
USE `maacsport` ;

-- -----------------------------------------------------
-- Table `maacsport`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`person` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`person` (
  `person_id` VARCHAR(11) NOT NULL,
  `person_name` VARCHAR(40) NOT NULL,
  `person_email` VARCHAR(40) NULL,
  `person_tfo` VARCHAR(20) NULL,
  `person_creation` DATETIME NOT NULL,
  `person_dropout` DATETIME NULL,
  `person_description` VARCHAR(45) NULL,
  `person_update` DATETIME NULL,
  `person_status` TINYINT(4) NULL,
  `person_ismale` TINYINT(1) NULL,
  `person_borndate` TIMESTAMP NULL,
  `person_dni` VARCHAR(11) NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maacsport`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`category` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`category` (
  `catetegory_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(20) NOT NULL,
  `category_creation` DATETIME NULL,
  `category_update` DATETIME NULL,
  `category_off` TINYINT(1) NULL,
  PRIMARY KEY (`catetegory_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maacsport`.`recinto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`recinto` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`recinto` (
  `recinto_id` INT NOT NULL AUTO_INCREMENT,
  `recinto_name` VARCHAR(45) NOT NULL,
  `recinto_creation` DATETIME NULL,
  `recinto_description` VARCHAR(45) NULL,
  `recinto_update` DATETIME NULL,
  `recinto_off` TINYINT(1) NULL,
  PRIMARY KEY (`recinto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maacsport`.`category_has_person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`category_has_person` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`category_has_person` (
  `Category_catetegory_id` INT NOT NULL,
  `person_person_id` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`Category_catetegory_id`, `person_person_id`),
  CONSTRAINT `fk_Category_has_person_Category`
    FOREIGN KEY (`Category_catetegory_id`)
    REFERENCES `maacsport`.`category` (`catetegory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Category_has_person_person1`
    FOREIGN KEY (`person_person_id`)
    REFERENCES `maacsport`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Category_has_person_person1_idx` ON `maacsport`.`category_has_person` (`person_person_id` ASC);

CREATE INDEX `fk_Category_has_person_Category_idx` ON `maacsport`.`category_has_person` (`Category_catetegory_id` ASC);


-- -----------------------------------------------------
-- Table `maacsport`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`reservation` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`reservation` (
  `reservation_id` INT NOT NULL AUTO_INCREMENT,
  `reservation_start` DATETIME NULL,
  `reservation_end` DATETIME NULL,
  `reservation_price` DOUBLE NULL,
  `reservation_paid` TINYINT(1) NULL,
  `reservation_creation` DATETIME NULL,
  `reservation_update` DATETIME NULL,
  `person_person_id` VARCHAR(11) NOT NULL,
  `recinto_recinto_id` INT NOT NULL,
  `reservation_status` TINYINT NULL,
  `reservation_day` INT NULL,
  PRIMARY KEY (`reservation_id`),
  CONSTRAINT `fk_reservation_person1`
    FOREIGN KEY (`person_person_id`)
    REFERENCES `maacsport`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_recinto1`
    FOREIGN KEY (`recinto_recinto_id`)
    REFERENCES `maacsport`.`recinto` (`recinto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_reservation_person1_idx` ON `maacsport`.`reservation` (`person_person_id` ASC);

CREATE INDEX `fk_reservation_recinto1_idx` ON `maacsport`.`reservation` (`recinto_recinto_id` ASC);


-- -----------------------------------------------------
-- Table `maacsport`.`activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`activity` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`activity` (
  `activity_id` INT NOT NULL,
  `activity_name` VARCHAR(45) NULL,
  `activity_creation` VARCHAR(45) NULL,
  `activity_update` VARCHAR(45) NULL,
  `activity_off` TINYINT(1) NULL,
  PRIMARY KEY (`activity_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maacsport`.`tournament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`tournament` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`tournament` (
  `t_id` INT NOT NULL,
  `t_name` VARCHAR(45) NULL,
  `t_creation` DATETIME NULL,
  `t_start` DATETIME NULL,
  `t_end` DATETIME NULL,
  `t_finished` TINYINT(1) NULL,
  `t_description` VARCHAR(45) NULL,
  `t_update` DATETIME NULL,
  PRIMARY KEY (`t_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maacsport`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`game` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`game` (
  `game_id` INT NOT NULL,
  `game_date` DATETIME NULL,
  `game_creation` DATETIME NULL,
  `game_result` VARCHAR(45) NULL,
  `game_update` DATETIME NULL,
  `tournament_t_id` INT NOT NULL,
  `activity_activity_id` INT NOT NULL,
  PRIMARY KEY (`game_id`),
  CONSTRAINT `fk_game_tournament1`
    FOREIGN KEY (`tournament_t_id`)
    REFERENCES `maacsport`.`tournament` (`t_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_activity1`
    FOREIGN KEY (`activity_activity_id`)
    REFERENCES `maacsport`.`activity` (`activity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_game_tournament1_idx` ON `maacsport`.`game` (`tournament_t_id` ASC);

CREATE INDEX `fk_game_activity1_idx` ON `maacsport`.`game` (`activity_activity_id` ASC);


-- -----------------------------------------------------
-- Table `maacsport`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`team` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`team` (
  `team_id` INT NOT NULL,
  `team_creation` DATETIME NULL,
  `team_description` VARCHAR(45) NULL,
  `team_off` TINYINT(1) NULL,
  `team_update` DATETIME NULL,
  PRIMARY KEY (`team_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maacsport`.`person_has_team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`person_has_team` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`person_has_team` (
  `person_person_id` VARCHAR(11) NOT NULL,
  `team_team_id` INT NOT NULL,
  PRIMARY KEY (`person_person_id`, `team_team_id`),
  CONSTRAINT `fk_person_has_team_person1`
    FOREIGN KEY (`person_person_id`)
    REFERENCES `maacsport`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_has_team_team1`
    FOREIGN KEY (`team_team_id`)
    REFERENCES `maacsport`.`team` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_person_has_team_team1_idx` ON `maacsport`.`person_has_team` (`team_team_id` ASC);

CREATE INDEX `fk_person_has_team_person1_idx` ON `maacsport`.`person_has_team` (`person_person_id` ASC);


-- -----------------------------------------------------
-- Table `maacsport`.`tournament_has_team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`tournament_has_team` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`tournament_has_team` (
  `tournament_t_id` INT NOT NULL,
  `team_team_id` INT NOT NULL,
  PRIMARY KEY (`tournament_t_id`, `team_team_id`),
  CONSTRAINT `fk_tournament_has_team_tournament1`
    FOREIGN KEY (`tournament_t_id`)
    REFERENCES `maacsport`.`tournament` (`t_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tournament_has_team_team1`
    FOREIGN KEY (`team_team_id`)
    REFERENCES `maacsport`.`team` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tournament_has_team_team1_idx` ON `maacsport`.`tournament_has_team` (`team_team_id` ASC);

CREATE INDEX `fk_tournament_has_team_tournament1_idx` ON `maacsport`.`tournament_has_team` (`tournament_t_id` ASC);


-- -----------------------------------------------------
-- Table `maacsport`.`game_has_team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`game_has_team` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`game_has_team` (
  `game_game_id` INT NOT NULL,
  `team_team_id` INT NOT NULL,
  `ght_won` TINYINT(1) NULL,
  PRIMARY KEY (`game_game_id`, `team_team_id`),
  CONSTRAINT `fk_game_has_team_game1`
    FOREIGN KEY (`game_game_id`)
    REFERENCES `maacsport`.`game` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_has_team_team1`
    FOREIGN KEY (`team_team_id`)
    REFERENCES `maacsport`.`team` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_game_has_team_team1_idx` ON `maacsport`.`game_has_team` (`team_team_id` ASC);

CREATE INDEX `fk_game_has_team_game1_idx` ON `maacsport`.`game_has_team` (`game_game_id` ASC);


-- -----------------------------------------------------
-- Table `maacsport`.`Language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`Language` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`Language` (
  `language_id` INT NOT NULL AUTO_INCREMENT,
  `language` VARCHAR(45) NULL,
  `creadtion_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`language_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maacsport`.`content_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`content_type` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`content_type` (
  `content_type_id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(700) NULL,
  `creation_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  `value_html` VARCHAR(1000) NULL,
  `Language_language_id` INT NOT NULL,
  PRIMARY KEY (`content_type_id`),
  CONSTRAINT `fk_content_type_Language1`
    FOREIGN KEY (`Language_language_id`)
    REFERENCES `maacsport`.`Language` (`language_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_content_type_Language1_idx` ON `maacsport`.`content_type` (`Language_language_id` ASC);


-- -----------------------------------------------------
-- Table `maacsport`.`credential_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`credential_type` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`credential_type` (
  `credential_type_id` INT NOT NULL AUTO_INCREMENT,
  `content_type_content_type_id` INT NOT NULL,
  `validation_pattern` VARCHAR(20) NULL DEFAULT '^[0-9a-zA-Z]{6,20}$' COMMENT '^.*$ - Todos	''^[0-9a-zA-Z]{6,20}$'' - Numero e letras de 6 a 20',
  `position_random_number` TINYINT(4) NULL DEFAULT 4,
  `min_length` TINYINT(4) NULL DEFAULT 8,
  `max_length` TINYINT(4) NULL DEFAULT 12,
  `max_validation_failure` TINYINT(4) NULL DEFAULT 3,
  `creation_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`credential_type_id`),
  CONSTRAINT `fk_credential_type_content_type1`
    FOREIGN KEY (`content_type_content_type_id`)
    REFERENCES `maacsport`.`content_type` (`content_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_credential_type_content_type1_idx` ON `maacsport`.`credential_type` (`content_type_content_type_id` ASC);


-- -----------------------------------------------------
-- Table `maacsport`.`channel_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`channel_type` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`channel_type` (
  `channel_id` INT NOT NULL AUTO_INCREMENT,
  `creation_date` DATETIME NULL,
  PRIMARY KEY (`channel_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maacsport`.`credential`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`credential` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`credential` (
  `credential_id` INT NOT NULL AUTO_INCREMENT,
  `credential_value` VARCHAR(45) NULL,
  `status_id` SMALLINT(6) NULL,
  `defined_by_user` TINYINT(4) NULL DEFAULT 0,
  `failure` SMALLINT(6) NULL DEFAULT 0,
  `last_positions` VARCHAR(20) NULL,
  `creation_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  `credential_type_credential_type_id` INT NOT NULL,
  `channel_type_channel_id` INT NOT NULL,
  `person_person_id` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`credential_id`, `person_person_id`),
  CONSTRAINT `fk_credential_credential_type1`
    FOREIGN KEY (`credential_type_credential_type_id`)
    REFERENCES `maacsport`.`credential_type` (`credential_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_credential_channel_type1`
    FOREIGN KEY (`channel_type_channel_id`)
    REFERENCES `maacsport`.`channel_type` (`channel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_credential_person1`
    FOREIGN KEY (`person_person_id`)
    REFERENCES `maacsport`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_credential_credential_type1_idx` ON `maacsport`.`credential` (`credential_type_credential_type_id` ASC);

CREATE INDEX `fk_credential_channel_type1_idx` ON `maacsport`.`credential` (`channel_type_channel_id` ASC);

CREATE INDEX `fk_credential_person1_idx` ON `maacsport`.`credential` (`person_person_id` ASC);


-- -----------------------------------------------------
-- Table `maacsport`.`user_device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`user_device` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`user_device` (
  `device_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `creation_date` DATETIME NULL,
  `person_person_id` VARCHAR(11) NOT NULL,
  `physic_device_id` VARCHAR(150) NULL,
  `physic_device_status` TINYINT(4) NULL DEFAULT 1,
  `update_date` DATETIME NULL,
  `device_value` VARCHAR(150) NULL,
  PRIMARY KEY (`device_id`),
  CONSTRAINT `fk_user_device_person1`
    FOREIGN KEY (`person_person_id`)
    REFERENCES `maacsport`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_user_device_person1_idx` ON `maacsport`.`user_device` (`person_person_id` ASC);


-- -----------------------------------------------------
-- Table `maacsport`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`sessions` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`sessions` (
  `session_id` VARCHAR(100) NOT NULL,
  `person_id` VARCHAR(11) NULL,
  `channel_type` TINYINT(4) NULL,
  `device` VARCHAR(100) NULL,
  `IP` VARCHAR(20) NULL,
  `deviceVersion` VARCHAR(100) NULL,
  `others` VARCHAR(100) NULL,
  PRIMARY KEY (`session_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maacsport`.`bono_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`bono_type` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`bono_type` (
  `bono_type_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `hours` INT NULL,
  `night` TINYINT(1) NULL,
  `creation_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`bono_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maacsport`.`bono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`bono` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`bono` (
  `bono_id` INT NOT NULL AUTO_INCREMENT,
  `creation_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  `price` DOUBLE NULL,
  `hours` INT NULL,
  `bono_type_bono_type_id` INT NOT NULL,
  `person_person_id` VARCHAR(11) NOT NULL,
  `terminated` TINYINT(1) NULL,
  PRIMARY KEY (`bono_id`),
  CONSTRAINT `fk_bono_bono_type1`
    FOREIGN KEY (`bono_type_bono_type_id`)
    REFERENCES `maacsport`.`bono_type` (`bono_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bono_person1`
    FOREIGN KEY (`person_person_id`)
    REFERENCES `maacsport`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_bono_bono_type1_idx` ON `maacsport`.`bono` (`bono_type_bono_type_id` ASC);

CREATE INDEX `fk_bono_person1_idx` ON `maacsport`.`bono` (`person_person_id` ASC);


-- -----------------------------------------------------
-- Table `maacsport`.`reservation_has_bono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`reservation_has_bono` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`reservation_has_bono` (
  `reservation_reservation_id` INT NOT NULL,
  `bono_bono_id` INT NOT NULL,
  `creation_date` DATETIME NULL,
  PRIMARY KEY (`reservation_reservation_id`, `bono_bono_id`),
  CONSTRAINT `fk_reservation_has_bono_reservation1`
    FOREIGN KEY (`reservation_reservation_id`)
    REFERENCES `maacsport`.`reservation` (`reservation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_has_bono_bono1`
    FOREIGN KEY (`bono_bono_id`)
    REFERENCES `maacsport`.`bono` (`bono_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_reservation_has_bono_bono1_idx` ON `maacsport`.`reservation_has_bono` (`bono_bono_id` ASC);

CREATE INDEX `fk_reservation_has_bono_reservation1_idx` ON `maacsport`.`reservation_has_bono` (`reservation_reservation_id` ASC);


-- -----------------------------------------------------
-- Table `maacsport`.`v_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`v_type` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`v_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `amount` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maacsport`.`v_person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`v_person` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`v_person` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `surname` VARCHAR(30) NOT NULL,
  `bornDate` TIMESTAMP NULL,
  `isWoman` TINYINT(1) NOT NULL,
  `join_date` TIMESTAMP NULL,
  `email` VARCHAR(45) NOT NULL,
  `tfo` VARCHAR(20) NOT NULL,
  `city` VARCHAR(20) NOT NULL,
  `cp` VARCHAR(8) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `v_type_id` INT NOT NULL,
  `description` VARCHAR(80) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `dropout_date` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_v_person_v_type1`
    FOREIGN KEY (`v_type_id`)
    REFERENCES `maacsport`.`v_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_v_person_v_type1_idx` ON `maacsport`.`v_person` (`v_type_id` ASC);


-- -----------------------------------------------------
-- Table `maacsport`.`v_quota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maacsport`.`v_quota` ;

CREATE TABLE IF NOT EXISTS `maacsport`.`v_quota` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quota_date` TIMESTAMP NULL,
  `creation_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `amount` DOUBLE NOT NULL,
  `name` VARCHAR(55) NOT NULL,
  `concept` VARCHAR(45) NOT NULL,
  `discount` DOUBLE NOT NULL,
  `token` VARCHAR(100) NOT NULL,
  `amount_char` VARCHAR(60) NOT NULL,
  `v_person_id` VARCHAR(10) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_v_quota_v_person1`
    FOREIGN KEY (`v_person_id`)
    REFERENCES `maacsport`.`v_person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_v_quota_v_person1_idx` ON `maacsport`.`v_quota` (`v_person_id` ASC);

SET SQL_MODE = '';
GRANT USAGE ON *.* TO maaguilera;
 DROP USER maaguilera;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'maaguilera' IDENTIFIED BY 'santaella';

GRANT ALL ON `maacsport`.* TO 'maaguilera';
GRANT SELECT, INSERT, TRIGGER ON TABLE `maacsport`.* TO 'maaguilera';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `maacsport`.* TO 'maaguilera';
GRANT EXECUTE ON ROUTINE `maacsport`.* TO 'maaguilera';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `maacsport`;

DELIMITER $$

USE `maacsport`$$
DROP TRIGGER IF EXISTS `maacsport`.`person_BINS` $$
USE `maacsport`$$


CREATE TRIGGER `person_BINS` BEFORE INSERT ON person FOR EACH ROW
-- Edit trigger body code below this line. Do not edit lines above this one
BEGIN  
        SET NEW.person_CREATION = NOW();   
        SET NEW.person_UPDATE = NOW();  
		SET new.PERSON_off = false; 
END
$$


USE `maacsport`$$
DROP TRIGGER IF EXISTS `maacsport`.`USER_DEVICE_UPDATE` $$
USE `maacsport`$$


CREATE TRIGGER `USER_DEVICE_UPDATE` BEFORE UPDATE ON user_device FOR EACH ROW
-- Edit trigger body code below this line. Do not edit lines above this one
BEGIN  
        SET NEW.UPDATE_DATE = NOW();   
END
$$


USE `maacsport`$$
DROP TRIGGER IF EXISTS `maacsport`.`user_device_BINS` $$
USE `maacsport`$$
$$


DELIMITER ;
